### ISSUE TITLE
pulumi preview not providing correct output for privilege revokes on schema

### ISSUE THREAD

**Issue by anitalySuper** [pulumi/pulumi-snowflake#640]
### Describe what happened

Revoking privileges on a schema, while keeping 1 privilege that is currently granted. When running pulumi preview after the code change, output states all privileges will be revoked.

### Sample program

I have a pulumi.yaml file with the following resource:
```
name: snowflake-schema-grants
runtime: yaml
description: A Snowflake YAML Pulumi stack for schema object to role grants.
config: {'pulumi:tags': {value: {'pulumi:template': yaml}}}
options:
  refresh: always

resources:
  snowflake-analyst--false--onschema--onschema--db-staging-accounts-public--without-grant-option--schema-to-role--grant:
    type: snowflake:GrantPrivilegesToAccountRole
    properties:
      accountRoleName: '"SNOWFLAKE_ANALYST"'
      onSchema:
        schemaName: '"DB_STAGING"."ACCOUNTS_PUBLIC"'
      privileges:
        - CREATE EXTERNAL TABLE
        - CREATE TABLE
        - CREATE VIEW
        - CREATE TEMPORARY TABLE
        - USAGE
        - CREATE MATERIALIZED VIEW
```

I then remove 5 of the privileges (CREATE EXTERNAL TABLE, CREATE TABLE, CREATE VIEW, CREATE TEMPORARY TABLE, CREATE MATERIALIZED VIEW)
```
name: snowflake-schema-grants
runtime: yaml
description: A Snowflake YAML Pulumi stack for schema object to role grants.
config: {'pulumi:tags': {value: {'pulumi:template': yaml}}}
options:
  refresh: always

resources:
  snowflake-analyst--false--onschema--onschema--db-staging-accounts-public--without-grant-option--schema-to-role--grant:
    type: snowflake:GrantPrivilegesToAccountRole
    properties:
      accountRoleName: '"SNOWFLAKE_ANALYST"'
      onSchema:
        schemaName: '"DB_STAGING"."ACCOUNTS_PUBLIC"'
      privileges:
        - USAGE
```
Then I run `pulumi preview --stack prod --diff --refresh=false`.

Preview says all privileges will be revoked.

### Log output

```
Previewing update (prod):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:prod::snowflake-schema-grants::pulumi:pulumi:Stack::snowflake-schema-grants-prod]
warning: provider config warning: Use `user` instead of `username`
    ~ snowflake:index/grantPrivilegesToAccountRole:GrantPrivilegesToAccountRole: (update)
        [id=SNOWFLAKE_ANALYST|false|false|CREATE TABLE,CREATE VIEW,CREATE EXTERNAL TABLE,CREATE TEMPORARY TABLE,USAGE,CREATE MATERIALIZED VIEW|OnSchema|OnSchema|"DB_STAGING"."ACCOUNTS_PUBLIC"]
        [urn=urn:pulumi:prod::snowflake-schema-grants::snowflake:index/grantPrivilegesToAccountRole:GrantPrivilegesToAccountRole::snowflake-analyst--false--onschema--onschema--db-staging-accounts-public--without-grant-option--schema-to-role--grant]
      ~ privileges: [
          - [0]: "CREATE EXTERNAL TABLE"
          - [1]: "CREATE TABLE"
          - [2]: "CREATE VIEW"
          - [3]: "CREATE TEMPORARY TABLE"
          - [4]: "USAGE"
          - [5]: "CREATE MATERIALIZED VIEW"
        ]
```

### Affected Resource(s)

snowflake:GrantPrivilegesToAccountRole

### Output of `pulumi about`

CLI          
Version      3.119.0
Go Version   go1.22.3
Go Compiler  gc

Plugins
KIND      NAME       VERSION
resource  snowflake  unknown
language  yaml       unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in yaml

Backend        
Name           coder-anitaly-coder-dev
URL            file:///workspace/snowflake-infra/infrastructure
User           coder
Organizations  
Token type     personal

No dependencies found

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: No current stack

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Hey @anitalySuper, thanks for reporting the issue here and sorry you had trouble with this.

We'll have a look as soon as possible.

As a workaround, is the issue fixed by refresh / running pulumi up again?

**Comment by VenelinMartinov** [comment]
Confirmed this reproes with the following program:

<details> <summary> Program </summary>

```yaml
name: privilege_revoke
runtime: yaml
description: ""
config:
  pulumi:tags:
    value:
      pulumi:template: https://www.pulumi.com/ai/api/project/57032551-9a24-46b5-b9b0-3a50c3bbb86e.zip
resources:
  myDatabase:
    type: snowflake:Database
    properties:
      name: my_database
      comment: This is my Snowflake database
  mySchema:
    type: snowflake:Schema
    properties:
      name: my_custom_schema
      comment: This is a custom schema in Snowflake
      database: ${myDatabase.name}
  myRole:
    type: snowflake:Role
    properties:
      name: SNOWFLAKE_ANALYST
      comment: This is a custom role in Snowflake
  snowflake-privileges:
    type: snowflake:GrantPrivilegesToAccountRole
    properties:
      accountRoleName: ${myRole.name}
      onSchema:
        schemaName: "${myDatabase.name}.${mySchema.name}"
      privileges:
        # - CREATE EXTERNAL TABLE
        # - CREATE TABLE
        # - CREATE VIEW
        # - CREATE TEMPORARY TABLE
        - USAGE
```

</details>
